server:
  port: 8081

spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 48b4292b-0ff3-442f-94ea-b5320aaa4d0c
