server:
  port: 8081

spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 48b4292b-0ff3-442f-94ea-b5320aaa4d0c

    sentinel:
      # 和Sentinel控制台DashBoard通讯，|| port：当前项目Http Server ip地址，|| dashboard：Sentinel 控制台DashBoard的地址
      transport:
        # 这个端口配置会在应用对应的机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互。比如 Sentinel 控制台添加了1个限流规则，会把规则数据 push 给这个 Http Server 接收，Http Server 再将规则注册到 Sentinel 中
        port: 8719
        # Sentinel DashBoard的地址
        dashboard: 127.0.0.1:8888
