server:
  port: 8080

spring:
  application:
    name: alibaba-nacos-discovery-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 48b4292b-0ff3-442f-94ea-b5320aaa4d0c

    sentinel:
      transport:
        dashboard: 127.0.0.1:8888

logging:
  level:
    org:
      springframework:
        cloud: TRACE


